name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-macos:
    name: macOS Tests
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
        
      - name: Swift Version
        run: swift --version
        
      - name: Build
        run: swift build
        
      - name: Run Tests
        run: swift test --parallel
        
  test-linux:
    name: Linux Tests
    runs-on: ubuntu-latest
    container:
      image: swift:6.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Swift Version
        run: swift --version
        
      - name: Build
        run: swift build
        
      - name: Run Tests
        run: swift test --parallel

